# Generated by Django 5.2.14 on 2026-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoadmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=150)),
                ('current_year', models.CharField(max_length=50)),
                ('career_interest', models.TextField()),
                ('skill_level', models.CharField(max_length=50)),
                ('existing_skills', models.TextField()),
                ('learning_time', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=150)),
                ('generated_roadmap', models.JSONField(default=dict)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('completed_topics', models.TextField(blank=True, default='')),
                ('learning_streak', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
